### ISSUE TITLE
 UI changes for the authenticator activity

### ISSUE THREAD

**Issue by Neha--Agarwal** [matobet/moVirt#106]
I would like to propose some UI changes for the authenticator activity. Please review the images and give me your inputs.
Suggested changed UI:
![screenshot_2015-08-12-14-17-34](https://cloud.githubusercontent.com/assets/7809127/9220822/df8ae404-4102-11e5-9d5a-2021fd2988f8.png)
Current UI:
![screenshot_2015-08-12-10-23-20](https://cloud.githubusercontent.com/assets/7809127/9220834/00ebb920-4103-11e5-850d-a1696bdcf536.png)

**Comment by sphoorti** [comment]
The TextView and EditText both mean the same. You could use a small thumbnail to depict the intended action. Attaching a sample screenshot of what I intend to say. The sample UI is not from movirt but I had seen it in another application.
![sample_wireframe_1](https://cloud.githubusercontent.com/assets/2352300/9221326/25515e4c-4107-11e5-9350-959f04c9055d.png)

This could enhance the UI.

**Comment by NoiseDoll** [comment]
@Neha--Agarwal Thanks for your effort, but UI is already improved the way you shown, but the code is on review at this moment.
https://github.com/matobet/moVirt/pull/105

**Comment by jelkosz** [comment]
@Neha--Agarwal but if you are interested in enhancing the UX of moVirt you could try to go this direction: https://github.com/matobet/moVirt/issues/107

**Comment by Neha--Agarwal** [comment]
Sure I'll give my best to it.

**Comment by jelkosz** [comment]
https://github.com/matobet/moVirt/pull/105 merged and the version of moVirt released - closing
