### ISSUE TITLE
Replace the current search box with something nicer

### ISSUE THREAD

**Issue by jelkosz** [matobet/moVirt#107]
The current search box is really ugly - it would be nice if it would use some more standard/nice way of doing this.

**Comment by Neha--Agarwal** [comment]
Let me know your views on this.
![screenshot_2015-08-13-11-40-24](https://cloud.githubusercontent.com/assets/7809127/9244538/c0090464-41b9-11e5-9071-17f2a0aba47e.png)

**Comment by jelkosz** [comment]
Hi Neha,

certainly much nicer but on the other hand it eats up more space on the limited screen size. What if this would show up only after some button clicked? Something like in gmail application?

**Comment by Neha--Agarwal** [comment]
Thanks for the review. I'll look for the best UI for the search box and change it accordingly keeping the space constraint in mind.

**Comment by Neha--Agarwal** [comment]
![screenshot from 2015-08-13 18 42 40](https://cloud.githubusercontent.com/assets/7809127/9250575/c842e23a-41eb-11e5-89b3-c5ce4c7abd6d.png)
On clicking the float button containing magnifying glass, this screen will show. Please ignore the spinner in the middle of screen.
![screenshot from 2015-08-13 18 44 50](https://cloud.githubusercontent.com/assets/7809127/9250588/e4558ebe-41eb-11e5-8c44-546a6566c682.png)

**Comment by NoiseDoll** [comment]
@Neha--Agarwal I may suggest to try to use Floating Action Button in combination with toolbar.
http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions
But Floating Action Buttons is quite new and I'm not sure how they would work on older devices and also there are not so many good guides on implementing this UI component...

**Comment by Neha--Agarwal** [comment]
@NoiseDoll The wireframes I've posted to use the same float action button which you've mentioned. It works perfectly for API level 7+. Even if there's any problem, there's always a way out using ImageButton and some extra coding.

**Comment by jelkosz** [comment]
@Neha--Agarwal well, I like this proposal a lot. If you are willing to implement it, please go ahead. If you will need any help with some setup or so, please feel free to contact anyone from us or drop a mail to movirt@ovirt.org.

**Comment by Neha--Agarwal** [comment]
I'm glad you liked it. I'll code it soon and ask for help if required. Thanks.

**Comment by jelkosz** [comment]
@Neha--Agarwal any progress? Are you stuck somewhere? Some issues I could maybe help with?

**Comment by sphoorti** [comment]
Hi Tomas,

Me and Neha have been trying to setup the ovirt all in one iso on a VM with
4gb RAM. However we are facing setup issue since after successful
installation and reboot, the screen hangs on loading icon. Could you help
us with this?

**Comment by sphoorti** [comment]
He Sphoorti, Neha,

well, not sure what exactly can be the issue, so just some recommendations:
1: please make sure the VMX is enabled on the virtualized processor. 
   - first make sure in the BIOS of the physical machine on which you run the virtual machine the hardware virtualization is enabled
   - than make sure that the virtual machine has this enabled (in virt-manager you can simply go to processor-> configuration -> pick "copy host CPU Configuration")
2: during boot you can press "esc" key and see some boot logs, maybe there will be something useful
3: try some different version of the all-in-one
4: try the ovirt-live (http://www.ovirt.org/OVirt_Live) which is a live ISO. Just burn this to some CD or put to an USB stick and boot from it. It should be stateless and setup itself. Or you can boot a virtual machine from it.

Please let me know if something of this helped.

Tomas


----- Original Message -----
> From: "Sphoorti Joglekar" <sphoorti.joglekar@gmail.com>
> To: "matobet/moVirt"
> <reply@reply.github.com>,
> "Tomas Jelinek" <tjelinek@redhat.com>
> Cc: "matobet/moVirt" <moVirt@noreply.github.com>
> Sent: Monday, August 31, 2015 11:57:05 AM
> Subject: Re: [moVirt] Replace the current search box with something nicer (#107)
> 
> Hi Tomas,
> 
> Me and Neha have been trying to setup the ovirt all in one iso on a VM with
> 4gb RAM. However we are facing setup issue since after successful
> installation and reboot, the screen hangs on loading icon. Could you help
> us with this?

**Comment by Neha--Agarwal** [comment]
I'm installing ovirt-live in VirtualBox on Ubuntu giving 6 GB of base memory. But when after installation, the machine reboots, it gets stuck on a blank black screen. I'll try out other solutions.

**Comment by jelkosz** [comment]
already implemented and released, closing
