### ISSUE TITLE
Re-evaluate minimum supported android version

### ISSUE THREAD

**Issue by matobet** [matobet/moVirt#135]
We currently state in manifest that we support 4.0 which I am not sure is still the case. There is also a lot of features in 4.1 that require workarounds to work for 4.0. 

We should test whether moVirt still fully functions on 4.0 and also use this issue to track all occurrences of 4.0 workarounds, that should be ultimately removed when we decide to bump the minimum to 4.1.

**Comment by suomiy** [comment]
up button doesn't work for versions 4.0 and lower, needs special handling

**Comment by matobet** [comment]
As of d123f56004d1e4b6b1a9738435f5edbf7e5a7615 (moVirt 1.3 RC1) the API Level 16 is the minimum requirement - which corresponds to Android 4.1 Jelly Bean. This bump was necessary in order to facilitate development of new features as well as maintenance of existing functionality.
