### ISSUE TITLE
Formatting of the DASHBOARD text on MainActivity Page

### ISSUE THREAD

**Issue by sphoorti** [matobet/moVirt#158]
In the labels, the Dashboard text is in upper case while other texts like All clusters and Settings are in lower case.

**Comment by suomiy** [comment]
@sphoorti this is default behaviour for all menu items. That means item is upper case if it is shown in the actionbar and lower case if it is hidden in the menu.

**Comment by jelkosz** [comment]
For consistency with the rest of the menu items, closing
