### ISSUE TITLE
In "sort by" the ASC and DESC is not so clear

### ISSUE THREAD

**Issue by shiramax** [matobet/moVirt#208]
name  should be from A to Z and from Z to A
cpu usage/mem usage should be from high to low and from low to high

the status is different, if you choose ASC i shows the down vm first? so it should be also from A to Z ? i'm not sure..

**Comment by suomiy** [comment]
you are right, this would make more sense.

The status is also sorted alphabetically, so I guess from A to Z would be right descriptor.
