### ISSUE TITLE
In the "DASHBOARD" the  storage it not clickable as the cpu and memory 

### ISSUE THREAD

**Issue by shiramax** [matobet/moVirt#211]

**Comment by jelkosz** [comment]
@suomiy do you remember if there is a reason for this? I'd say it should move you to the storage tab

**Comment by suomiy** [comment]
@jelkosz I am not sure, but the reason may be that we don't have implemented sort by size in storage tab yet

**Comment by suomiy** [comment]
maybe also because we get some storages with unknown size

**Comment by suomiy** [comment]
I will fix this for physical tab to redirect to storage domains sorted by status. But this cannot be done for the virtual tab because we don't have a tab for  all disks
