### ISSUE TITLE
add support for hierarchical certificates

### ISSUE THREAD

**Issue by jelkosz** [matobet/moVirt#214]
If the oVirt is using a CA which has been signed by a CA which is not trusted by the device, there is currently no way how to make movirt work securely with this setup.

The reason is that moVirt either trusts all CAs (not secure), the CAs which come with the device (not the case described above) or a self signed CA which can be downloaded using moVirt.

This feature will add an option to download the whole chain of CAs using moVirt and work securely also in this kind of setups.

**Comment by shiramax** [comment]
in "Trust Specific Certificate" , the "valid for hostnames" should be shown only after the CA has been downloaded

**Comment by suomiy** [comment]
fixed in #219 
> in "Trust Specific Certificate" , the "valid for hostnames" should be shown only after the CA has been downloaded

**Comment by jelkosz** [comment]
fixed, closing
