### ISSUE TITLE
Remove 'Clear Local Events'

### ISSUE THREAD

**Issue by shiramax** [matobet/moVirt#226]
this feature is not needed anymore

**Comment by suomiy** [comment]
Why it is not needed? You can delete old events to speed up the application and save the disk space.

**Comment by shiramax** [comment]
this feature works until the next sync, and the sync action happens all the time, which it doesn't make sense to me.
also as I understood from @jelkosz, this feature was introduced  when movirt was very very rocky and it's not needed any more.

**Comment by suomiy** [comment]
I guess you are right.

**Comment by jelkosz** [comment]
@suomiy yep, she is right :) it used to be a rescue button when something went terribly wrong. Did not need to use it anymore, may go away now.
