### ISSUE TITLE
information given about Snapshot in the app is different form admin portal.

### ISSUE THREAD

**Issue by shiramax** [matobet/moVirt#227]
in the admin portal, the General tab present only : 
Defined Memory
Physical Memory Guaranteed
Number of CPU Cores

in the app the General tab in the Snapshot presents the General tab of the VM 

also, in the admin portal there is the 'Installed Applications' tab, this tab doesn't appear in the app.

**Comment by suomiy** [comment]
General tab is a state of a vm in time of the snapshot, which is valid behaviour. Although empty fields Host/Display Type are superfluous.

Installed Applications tab is unimportant feature now.

**Comment by shiramax** [comment]
@suomiy I Disagree, The title of the tab is : "Snapshot XXX" 
and the information is given is about the vm and not the snapshot, 
for example, the status presented in this tab is the status of the Vm and not the status of the Snapshot... 
This is not valid behaviour..

**Comment by suomiy** [comment]
@shiramax 
snapshot == vm in one point in history
we just show more information than oVirt
