### ISSUE TITLE
Dashboard: over commit is incorrect

### ISSUE THREAD

**Issue by suomiy** [matobet/moVirt#230]
- over commit should be ration of running/allocated virtual resources and total resources
- also this will introduce semantic changes to Virtual View

**Comment by shiramax** [comment]
@suomiy , which semantic changed will added to the virtual view?

**Comment by suomiy** [comment]
> which semantic changed will added to the virtual view?
- it was a usage of resources of running vms till now. Now it will be comparison of running/all vms.

Maybe we could leave current functionality, because this (feature?) is missing in oVirt dashboard. 
Thoughts?

**Comment by suomiy** [comment]
So the resolution is to keep current behaviour to display utilization of running vms and put explanation to wiki.

**Comment by suomiy** [comment]
It will be also clearer to remove over commit from virtual dashboard.

**Comment by suomiy** [comment]
reevaluate the meaning of 
> The CPU don't have the X Available of X GIB in the app (In the admin portal it's exists)

and remove the first allocated label

from #210

**Comment by shiramax** [comment]
I don't think that the Virtual Dashboard is necessary. 
In the physical Dashboard the information is necessary because i can see that there is lack of resources, and i can add resources or do other actions.
in the Virtual Dashboard, the sum of all usage of running vms  is not helping so much..

**Comment by suomiy** [comment]
I don't think giving a user more information (e.g. about running vms) is a problem

**Comment by shiramax** [comment]
it's not keeping it simple, and this can be confusing.

**Comment by suomiy** [comment]
@shiramax 
Fix for the dashboard is on the way.
I made a draft for documentation here: https://docs.google.com/document/d/1ngQHGjHX1GPAbquL489NetwcofRP_2UiXF6bVoMzyAc/edit?usp=sharing
Can you please tell me if something is missing or is not clear?
