### ISSUE TITLE
Preview Action appears only after performing preview in webadmin

### ISSUE THREAD

**Issue by shiramax** [matobet/moVirt#236]
The preview action doesn't appear in the app, only after performing this action in the webadmin i able to see preview and all other actions too..

**Comment by suomiy** [comment]
Please check that you have the same data as in webadmin. Try to refresh snapshots and vm.

Some actions are only accessible when vm is up/down and inaccessible if any snapshot is in LOCKED state.

Also you will not have current data, if you perform some action in moVirt and that action will take long time to execute in webadmin. You would have to refresh needed data manually after it is executed.

If the problem persist, please write me sequence of steps which lead to the problem and version of android.

**Comment by shiramax** [comment]
I have the same Data in the WebAdmin, 
the steps to reproduce :
1. create snapshot  
2. refresh and make sure that the status of the snapshot is OK 
3. click on the snapshot and see that there is no option to perform Preview.  (but via the admin portal it's possible)

i'm using Android 5.0

**Comment by shiramax** [comment]
closing this issue - The vm spouse to be powered off, and it wasn't when i tested it.
