### ISSUE TITLE
add quick fix suggestion to events

### ISSUE THREAD

**Issue by jelkosz** [matobet/moVirt#45]
The error events should contain some suggestions how to fix them with corresponding actions.

**Comment by jelkosz** [comment]
The problem with this issue is that it is hard to make any meaningful suggestions. I'll close this issue, if someone will come up with some good idea what to do here, please reopen

**Comment by mykaul** [comment]
@jelkosz - if you are talking about oVirt events - it's not hard, and we can always enumerate the top 3 possibilities, for example - but it belongs to oVirt, not to moVirt.
