### ISSUE TITLE
Implement Host UI

### ISSUE THREAD

**Issue by matobet** [matobet/moVirt#62]
Recent commit 876f1e1242a54a1c858155f09fa4cb597d580b8e added necessary infrastructure for Hosts. What is missing is similar details UI as we have for VM's (HostDetailActivity with HostDetailGeneralFragment, EventsFragment and NicDetailFragment).

**Comment by zyx0225** [comment]
Do you mean to add Hosts tab on main screen?

**Comment by matobet** [comment]
Host main tab is already implemented. Now we need to add the details activity that would show host info/statistics, possibly with tabs for events/nics as in the VmDetailsActivity case.

**Comment by zyx0225** [comment]
I see. I will add the details activity these days

**Comment by jelkosz** [comment]
in 1.0
