### ISSUE TITLE
Certificates doesn't work on Android 4.1.2 (API 16)

### ISSUE THREAD

**Issue by NoiseDoll** [matobet/moVirt#80]
![screenshot_2015-07-03-23-11-48](https://cloud.githubusercontent.com/assets/11350266/8499747/378d61b6-21d9-11e5-88d5-b99cde274f49.png)
![screenshot_2015-07-03-23-11-59](https://cloud.githubusercontent.com/assets/11350266/8499749/3cace130-21d9-11e5-8238-bdabfcabe167.png)

The same cert works on emulator with API 21.
![default](https://cloud.githubusercontent.com/assets/11350266/8499822/ddd755b8-21d9-11e5-9bb6-4ac5c08fe76d.jpg)

**Comment by jeffrade** [comment]
That specific cert was probably not included in 4.1.  Looks like more were added with 4.2.  You can maybe pin that cert in your app (see the link below).

["As of Android 4.2 (Jelly Bean), Android currently contains over 100 CAs that are updated in each release."](https://developer.android.com/training/articles/security-ssl.html#Concepts)

**Comment by jelkosz** [comment]
we were not able to simulate this, possibly it was an issue with the certificate itself on that particular installation of oVirt.
