### ISSUE TITLE
Previously downloaded cert disappears after updating DB scheme.

### ISSUE THREAD

**Issue by NoiseDoll** [matobet/moVirt#94]
This leads to exception.
![cert_missing](https://cloud.githubusercontent.com/assets/11350266/8852767/5ff3fbda-319a-11e5-96ad-612477a0fded.jpg)

If connection information persists after updating DB scheme it may be possible to download cert automatically after DB update and avoid this error.

**Comment by jelkosz** [comment]
should be fixed while implementing the https://github.com/matobet/moVirt/issues/214
