### ISSUE TITLE
Scanned host IDs requires lowercase letters

### ISSUE THREAD

**Issue by jniederm** [matobet/moVirt#98]
Hex digits a-f in host ids are required to be lowercase. One would expect it is case-insensitive.

Steps to reproduce:
1. Get id of host using REST api
2. Edit at least one a-f digit to uppercase in that id
3. Generate datamatrix (e.g. http://datamatrix.kaywa.com/) and scan it

Result: "NO SUCH HOST" message
Expected result: Host details shown.

**Comment by NoiseDoll** [comment]
Yes, you right, GUID should be case-insesitive. We'll fix it.

**Comment by jelkosz** [comment]
fixed in 1.0
