### ISSUE TITLE
Texts on scanning screen clashes

### ISSUE THREAD

**Issue by jniederm** [matobet/moVirt#99]
When the datamatrix is scanned, texts are rendered over each other, both for recognized host and unknown datamatrix.

![clash](https://cloud.githubusercontent.com/assets/5278760/8938331/505e967c-355e-11e5-9e17-bf4fae4c709d.png)
![clash2](https://cloud.githubusercontent.com/assets/5278760/8938332/5062bebe-355e-11e5-919a-24df8e961e9f.png)

**Comment by jelkosz** [comment]
fixed
